- name: Instalar Elasticsearch en nodos Debian
  hosts: debian_elasticsearch
  become: yes
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
      become: yes

    - name: Instalar paquetes necesarios
      apt:
        name:
          - default-jre
          - apt-transport-https
          - software-properties-common
        state: present
      become: yes

    - name: Agregar la clave pública de Elasticsearch
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes

    - name: Agregar el repositorio de Elasticsearch
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
      become: yes

    - name: Actualizar lista de paquetes nuevamente
      apt:
        update_cache: yes
      become: yes

    - name: Instalar Elasticsearch
      apt:
        name: elasticsearch
        state: present
      become: yes

