- name: Start Elasticsearch and configure the network
  hosts: debian_elasticsearch
  become: yes
  tasks:
    - name: Enable and start Elasticsearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started
      become: true
      when: inventory_hostname in groups['debian_elasticsearch']
